QA-1422: Updated TestRunner validation to check cluster specification.
DataBiosphere/terra-test-runner pull request #9
Opened 2021-03-25 22:53 UTC by ichengchang

Just a minor fix so GH action can run both resiliency tests and other test types.

Additional notes: The main purpose of this PR is to enable different types of tests (Integration / Resiliency) to use the same test configuration file. The assumption is that Integration tests do not need the `KubernetesClientUtils` to manipulate a cluster. So if developers have only integration tests in mind, the test config specification they create might not have the cluster specification and test runner validation will fail. If the assumption wasn't correct (as Mariko points out) then we need to figure out what would be the best way to use one test configuration for all test types.

Added @gjuggler to this Pull Request. Since Mariko is on vacation, I would like Dan and Greg to review and give this ticket a second eye. I can loop Mariko in once she's back from vacation.

2021-04-13 16:53 UTC, gjuggler commented on src/main/java/bio/terra/testrunner/runner/TestRunner.java
> +    if (!config.server.skipKubernetes && config.disruptiveScript != null) {
Just following up on old review requests: this doesn't feel like a straightforward change in the code, without either (1) a comment within the code explaining why we're including a check on the `disruptiveScript` field even though that field isn't accessed by any of the code within the conditional block, or (2) some rearrangement of the code to make it more obvious which scenario is being protected against.

It's also not obvious to me what this has to do with the linked ticket, which seems to be about validating domain-wide delegation capabilities. If there is a connection, it should be made more explicit in the PR description.

2021-04-15 13:20 UTC, ichengchang commented on src/main/java/bio/terra/testrunner/runner/TestRunner.java
> +    if (!config.server.skipKubernetes && config.disruptiveScript != null) {
I updated the PR with additional notes. So this PR wasn't directly related to domain-wide delegation per se, but it came up when merging test config for resiliency test into the one used by integration test. The purpose is to simplify and consolidate these config files into one config.

2021-04-19 15:02 UTC, marikomedlock requested changes

2021-04-19 15:02 UTC, marikomedlock commented on src/main/java/bio/terra/testrunner/runner/TestRunner.java
> +    if (!config.server.skipKubernetes && config.disruptiveScript != null) {
RE @ichengchang comment 24 days ago: I think this change is incorrect. We want to `buildKubernetesClientObjectWithClientKey` and `modifyKubernetesPostDeployment` when `skipKubernetes=false` always, regardless of whether a disruptive script is specified or not. Test scripts and application setup can also modify kubernetes. Disruptive scripts are not the only way.

I'm still confused about the error you're trying to address here, though. Can you point to a line that's throwing an exception and an example test config that triggers it?

2021-04-23 18:52 UTC, marikomedlock reviewed
This looks good to me.

Can you please update the PR description and make sure the spotless/spotbugs checks are passing?

2021-04-26 14:12 UTC, ichengchang commented
> This looks good to me.
> 
> Can you please update the PR description and make sure the spotless/spotbugs checks are passing?

Spotless check applied.

2021-04-26 14:20 UTC, marikomedlock approved these changes

2021-04-27 13:19 UTC, ddietterich approved these changes

2021-04-27 13:36 UTC, merged